import { Nft, NftSource, NftType } from './types'

export const IPFS_GATEWAY = 'https://nft.flyswap.shop'

export const nftSources: NftSource = {
  [NftType.BABYSWAP]: {
    address: {
      56: '0x9f0225d5c92b9cee4024f6406c4f13e546fd91a8',
      97: '0xA20E663B0BF8EAA7e05650Ff911Ab34efB842524',
    },
    identifierKey: 'image',
  }
}

const Nfts: Nft[] = [
  {
    nid: 0,
    name: 'Firstever Baby',
    category: 'Memories',
    description: 'Huge thanks to our 1st-month supporters, loneliness fades away with you accompany by.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/finalNFB.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/10001-28680.jpg",
    },
    vaule: '10 BABY',
    quantity: '18680',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 1,
    name: 'Panther in the House',
    category: 'Mates',
    description: 'Panther in the House',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/pantherNFB.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/28681-36405.jpg",
    },
    vaule: '10 BABY',
    quantity: '7725',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 2,
    name: 'Alpaca in the House',
    category: 'Mates',
    description: 'Alpaca in the House',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/alpacaNFB.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/36406-45612.jpg",
    },
    vaule: '10 BABY',
    quantity: '9207',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 3,
    name: 'UEFA EURO 2020 - Switzerland',
    category: 'Baby Squad',
    description: 'The Top 8 team in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/SWITZERLANDnfb.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2000001-2000125.jpg",
    },
    vaule: '1000 BABY',
    quantity: '125',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 4,  
    name: 'UEFA EURO 2020 - Spain',
    category: 'Baby Squad',
    description: 'The Top 8 team in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/SPAINnfb.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2000126-2000250.jpg",
    },
    vaule: '1000 BABY',
    quantity: '125',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 5,
    name: 'UEFA EURO 2020 - Belgium',
    category: 'Baby Squad',
    description: 'The Top 8 team in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/BELGIUMnfb.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2000251-2000375.jpg",
    },
    vaule: '1000 BABY',
    quantity: '125',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 6,
    name: 'UEFA EURO 2020 - Italy',
    category: 'Baby Squad',
    description: 'The Top 8 team in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/ITALYnfb.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2000376-2000500.jpg",
    },
    vaule: '1000 BABY',
    quantity: '125',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 7,
    name: 'UEFA EURO 2020 - Czech Republic',
    category: 'Baby Squad',
    description: 'The Top 8 team in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/CZECHREPUBLICnfb.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2000501-2000625.jpg",
    },
    vaule: '1000 BABY',
    quantity: '125',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 8,
    name: 'UEFA EURO 2020 - Denmark',
    category: 'Baby Squad',
    description: 'The Top 8 team in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/DENMARKnfb.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2000626-2000750.jpg",

    },
    vaule: '1000 BABY',
    quantity: '125',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 9,
    name: 'UEFA EURO 2020 - Ukraine',
    category: 'Baby Squad',
    description: 'The Top 8 team in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/UKRAINEnfb.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2000751-2000875.jpg",
    },
    vaule: '1000 BABY',
    quantity: '125',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 10,
    name: 'UEFA EURO 2020 - England​',
    category: 'Baby Squad',
    description: 'The Top 8 team in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/ENGLANDnfb.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2000876-2001000.jpg",
    },
    vaule: '1000 BABY',
    quantity: '125',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 11,
    name: 'Doggy in the House',
    category: 'Mates',
    description: 'Doggy in the House',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/doggyNFBfinal.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/45613-57852.jpg",
    },
    vaule: '10 BABY',
    quantity: '12240',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 12,
    name: 'UEFA EURO 2020 - MBAPPE',
    category: 'Baby Squad',
    description: 'Kylian Mbappé in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/MBAPPE.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2001001-2001156.jpg",
    },
    vaule: '1000 BABY',
    quantity: '156',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 13,
    name: 'UEFA EURO 2020 - KROOS',
    category: 'Baby Squad',
    description: 'Toni Kroos in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/KROOS.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2001157-2001271.jpg",
    },
    vaule: '1000 BABY',
    quantity: '115',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 14,
    name: 'UEFA EURO 2020 - MODRIC',
    category: 'Baby Squad',
    description: 'Luka Modric in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/MODRIC.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2001272-2001369.jpg",
    },
    vaule: '1000 BABY',
    quantity: '98',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 15,
    name: 'UEFA EURO 2020 - RONALDO',
    category: 'Baby Squad',
    description: 'Cristiano Ronaldo in UEFA EURO 2020.',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/RONALDO.gif',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/2001370-2001451.jpg",
    },
    vaule: '1000 BABY',
    quantity: '82',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 16,
    name: 'BABY & SHARK',
    category: 'Mates',
    description: 'BabySwap x BabyShark',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/BABY%26SHARK.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/57853-57995.jpg",
    },
    vaule: '100 BABY',
    quantity: '143',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 17,
    name: 'Bunny in the House',
    category: 'Mates',
    description: 'Bunny in the House',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/BPnfb.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/57996-62031.jpg",
    },
    vaule: '10 BABY',
    quantity: '4036',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 18,
    name: 'BABY & SAFEMARS',
    category: 'Mates',
    description: 'BabySwap x SafeMars',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/SafeMarsNFB.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/62032-62174.jpg",
    },
    vaule: '100 BABY',
    quantity: '143',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 19,
    name: 'BABY & CWS',
    category: 'Mates',
    description: 'BabySwap x Seascape',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/SeascapeNFB.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/62175-62317.jpg",
    },
    vaule: '100 BABY',
    quantity: '143',
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 20,
    name: 'Diamond Hand - July 2021',
    category: 'Family',
    description: 'Top 150 BABY Holders in July 2021, including Snack Pool staking and BABY-USDT farming',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/JUL2021diamondhandNFB.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/7000001-7000150.jpg",
    },
    vaule: '1000 BABY',
    quantity: "150",
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 21,
    name: 'Gold Miner - July 2021',
    category: 'Family',
    description: 'Top 50 BabySwap farmers in July 2021',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/JUL2021goldminerNfb.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/7000151-7000200.jpg",
    },
    vaule: '1000 BABY',
    quantity: "50",
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 22,
    name: 'BABY & HELMET',
    category: 'Mates',
    description: 'BabySwap x Helmet',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/helmetNFB.jpg',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/62318-62460.jpg",
    },
    vaule: '100 BABY',
    quantity: "143",
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 23,
    name: 'BABY & WTW',
    category: 'Mates',
    description: 'BabySwap x Watchtower',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/WTW+NFB.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/62461-62603.png",
    },
    vaule: '100 BABY',
    quantity: "143",
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  },
  {
    nid: 24,
    name: 'BABY & BNX',
    category: 'Mates',
    description: 'BabySwap x BinaryX',
    images: {
      lg: 'NFB(600*600).gif',
      md: 'mixie-1-md.png',
      sm: 'mixie-1-sm.png',
      ipfs: 'https://baby-upload.s3.ap-southeast-1.amazonaws.com/0730bnxNFB.png',
      sketch: "https://baby-upload.s3.ap-southeast-1.amazonaws.com/sketch/62604-62746.png",
    },
    vaule: '100 BABY',
    quantity: "143",
    sortOrder: 1,
    identifier: '001-Baby',
    type: NftType.BABYSWAP,
    variationId: 1,
  }
  // {
  //   name: "Cakeston Easter '21",
  //   description: 'Melting Easter eggs and melting hearts!',
  //   images: {
  //     lg: 'cakeston-easter-21-lg.png',
  //     md: 'cakeston-easter-21-md.png',
  //     sm: 'cakeston-easter-21-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmZGqWaovULNEMKxBCGnGjh27JQkAyadS6AW4J4Lzf3XBp/easter-caker.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'easter-caker',
  //   type: NftType.PANCAKE,
  //   variationId: 15,
  // },
  // {
  //   name: "Flipsie Easter '21",
  //   description: 'Watch out for Flipsie’s spatula smash!',
  //   images: {
  //     lg: 'flipsie-easter-21-lg.png',
  //     md: 'flipsie-easter-21-md.png',
  //     sm: 'flipsie-easter-21-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmZGqWaovULNEMKxBCGnGjh27JQkAyadS6AW4J4Lzf3XBp/easter-flipper.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'easter-flipper',
  //   type: NftType.PANCAKE,
  //   variationId: 14,
  // },
  // {
  //   name: "Stormy Easter '21",
  //   description: 'Do you like chocolate with your syrup? Go long!',
  //   images: {
  //     lg: 'stormy-easter-21-lg.png',
  //     md: 'stormy-easter-21-md.png',
  //     sm: 'stormy-easter-21-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmZGqWaovULNEMKxBCGnGjh27JQkAyadS6AW4J4Lzf3XBp/easter-storm.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'easter-storm',
  //   type: NftType.PANCAKE,
  //   variationId: 12,
  // },
  // {
  //   name: 'Bullish',
  //   description: 'Happy Niu Year! This bunny’s excited for the year of the bull (market!)',
  //   images: {
  //     lg: 'bullish-lg.png',
  //     md: 'bullish-md.png',
  //     sm: 'bullish-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmNS1A5HsRW1JvFWtGkm4o9TgZVe2P7kA8TB4yxvS6A7ms/bullish.png',
  //   },
  //   video: {
  //     webm: 'https://gateway.pinata.cloud/ipfs/QmNS1A5HsRW1JvFWtGkm4o9TgZVe2P7kA8TB4yxvS6A7ms/bullish.webm',
  //     mp4: 'https://gateway.pinata.cloud/ipfs/QmNS1A5HsRW1JvFWtGkm4o9TgZVe2P7kA8TB4yxvS6A7ms/bullish.mp4',
  //   },
  //   sortOrder: 999,
  //   identifier: 'bullish',
  //   type: NftType.PANCAKE,
  //   variationId: 11,
  // },
  // {
  //   name: 'Hiccup',
  //   description: "Oopsie daisy! Hiccup's had a bit of an accident. Poor little fella.",
  //   images: {
  //     lg: 'hiccup-lg.png',
  //     md: 'hiccup-md.png',
  //     sm: 'hiccup-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmQ6EE6gkVzAQUdQLLM7CyrnME6LZHCoy92ZERW8HXmyjw/hiccup.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'hiccup',
  //   type: NftType.PANCAKE,
  //   variationId: 10,
  // },
  // {
  //   name: 'Sleepy',
  //   description: 'Aww, looks like eating pancakes all day is tough work. Sweet dreams!',
  //   images: {
  //     lg: 'sleepy-lg.png',
  //     md: 'sleepy-md.png',
  //     sm: 'sleepy-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmYD9AtzyQPjSa9jfZcZq88gSaRssdhGmKqQifUDjGFfXm/sleepy.png',
  //     blur: 'sleepy-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'sleepy',
  //   type: NftType.PANCAKE,
  //   variationId: 5,
  // },
  // {
  //   name: 'Sunny',
  //   description: 'Sunny is always cheerful when there are pancakes around. Smile!',
  //   images: {
  //     lg: 'sunny-lg.png',
  //     md: 'sunny-md.png',
  //     sm: 'sunny-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmYD9AtzyQPjSa9jfZcZq88gSaRssdhGmKqQifUDjGFfXm/sunny.png',
  //     blur: 'sunny-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'sunny',
  //   type: NftType.PANCAKE,
  //   variationId: 9,
  // },
  // {
  //   name: 'Churro',
  //   description: "Don't let that dopey smile deceive you... Churro's a master CAKE chef!",
  //   images: {
  //     lg: 'churro-lg.png',
  //     md: 'churro-md.png',
  //     sm: 'churro-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmYD9AtzyQPjSa9jfZcZq88gSaRssdhGmKqQifUDjGFfXm/churro.png',
  //     blur: 'churro-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'churro',
  //   type: NftType.PANCAKE,
  //   variationId: 8,
  // },
  // {
  //   name: 'Dollop',
  //   description: "Nommm... Oh hi, I'm just meditating on the meaning of CAKE.",
  //   images: {
  //     lg: 'dollop-lg.png',
  //     md: 'dollop-md.png',
  //     sm: 'dollop-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmYD9AtzyQPjSa9jfZcZq88gSaRssdhGmKqQifUDjGFfXm/dollop.png',
  //     blur: 'dollop-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'dollop',
  //   type: NftType.PANCAKE,
  //   variationId: 6,
  // },
  // {
  //   name: 'Twinkle',
  //   description: "Three guesses what's put that twinkle in those eyes! (Hint: it's CAKE)",
  //   images: {
  //     lg: 'twinkle-lg.png',
  //     md: 'twinkle-md.png',
  //     sm: 'twinkle-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmYD9AtzyQPjSa9jfZcZq88gSaRssdhGmKqQifUDjGFfXm/twinkle.png',
  //     blur: 'twinkle-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'twinkle',
  //   type: NftType.PANCAKE,
  //   variationId: 7,
  // },
  // {
  //   name: 'Swapsies',
  //   description: 'These bunnies love nothing more than swapping pancakes. Especially on BSC.',
  //   images: {
  //     lg: 'swapsies-lg.png',
  //     md: 'swapsies-md.png',
  //     sm: 'swapsies-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmXdHqg3nywpNJWDevJQPtkz93vpfoHcZWQovFz2nmtPf5/swapsies.png',
  //     blur: 'swapsies-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'swapsies',
  //   type: NftType.PANCAKE,
  //   variationId: 0,
  // },
  // {
  //   name: 'Drizzle',
  //   description: "It's raining syrup on this bunny, but he doesn't seem to mind. Can you blame him?",
  //   images: {
  //     lg: 'drizzle-lg.png',
  //     md: 'drizzle-md.png',
  //     sm: 'drizzle-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmXdHqg3nywpNJWDevJQPtkz93vpfoHcZWQovFz2nmtPf5/drizzle.png',
  //     blur: 'drizzle-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'drizzle',
  //   type: NftType.PANCAKE,
  //   variationId: 1,
  // },
  // {
  //   name: 'Blueberries',
  //   description: "These bunnies like their pancakes with blueberries. What's your favorite topping?",
  //   images: {
  //     lg: 'blueberries-lg.png',
  //     md: 'blueberries-md.png',
  //     sm: 'blueberries-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmXdHqg3nywpNJWDevJQPtkz93vpfoHcZWQovFz2nmtPf5/blueberries.png',
  //     blur: 'blueberries-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'blueberries',
  //   type: NftType.PANCAKE,
  //   variationId: 2,
  // },
  // {
  //   name: 'Circular',
  //   description: "Love makes the world go 'round... but so do pancakes. And these bunnies know it.",
  //   images: {
  //     lg: 'circular-lg.png',
  //     md: 'circular-md.png',
  //     sm: 'circular-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmXdHqg3nywpNJWDevJQPtkz93vpfoHcZWQovFz2nmtPf5/circular.png',
  //     blur: 'circular-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'circular',
  //   type: NftType.PANCAKE,
  //   variationId: 3,
  // },
  // {
  //   name: 'Sparkle',
  //   description: 'It’s sparkling syrup, pancakes, and even lottery tickets! This bunny really loves it.',
  //   images: {
  //     lg: 'sparkle-lg.png',
  //     md: 'sparkle-md.png',
  //     sm: 'sparkle-sm.png',
  //     ipfs: 'https://gateway.pinata.cloud/ipfs/QmXdHqg3nywpNJWDevJQPtkz93vpfoHcZWQovFz2nmtPf5/sparkle.png',
  //     blur: 'sparkle-blur.png',
  //   },
  //   sortOrder: 999,
  //   identifier: 'sparkle',
  //   type: NftType.PANCAKE,
  //   variationId: 4,
  // },
]

export default Nfts
